name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          pip install poetry
          poetry --version
      - name: Install packages
        run: |
          poetry install
      - name: Check formatting
        run: |
          make check-formatting
      - name: Tests
        run: |
          make report-coverage
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v3
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          files: coverage.xml
#          fail_ci_if_error: true
#          verbose: true